### PR TITLE
docs: document selectors a bit better

### PR DESCRIPTION
**Pull request by OrKoN**

### CODE REVIEW

**Review by jrandolf — CHANGES_REQUESTED** [review]
Could we add something about `pierce/`?

**Comment by OrKoN** [comment]
what do you mean? we don't support `pierce/`

**Comment by jrandolf** [comment]
> pierce/

Ah, okay, I was under the assumption we did.

**Review by jrandolf — APPROVED** [review]

**Comment by OrKoN** [comment]
yeah, we don't record/generate `pierce/` selectors although if someone defines `pierce/` by hand and their runner is Puppeteer it'd probably work (but no explicit support for it).

**Pull request merged**
