### PR TITLE
feat: add `waitForURL` and `waitForElement` extensions

### PR DESCRIPTION
**Pull request by jrandolf**
This PR adds `waitForURL` and some additional properties to the `waitForElement` step. `waitForURL` is a new step that waits for the location of a frame to match a given url (either partially or fully). The additions to `waitForElement` include properties waiting and inverse checking (completely inverts the step).

### CODE REVIEW

**Comment by Josephus1123** [comment]
> This PR adds `waitForURL` and some additional properties to the `waitForElement` step. `waitForURL` is a new step that waits for the location of a frame to match a given url (either partially or fully). The additions to `waitForElement` include properties waiting and inverse checking (completely inverts the step).

https://github.com/puppeteer/replay/pull/408#issue-1496575166

**Comment by Josephus1123** [comment]
@Josephus1123

**Comment by Yaf532** [comment]
#

**Comment by badraly1** [comment]
> @Josephus1123

‏‪RMX3690_12.A.53‬‏

**Comment by catfishcrawler** [comment]
# Correct: # easy to match operators with operands income = (gross_wages + taxable_interest + (dividends - qualified_dividends) - ira_deduction - student_loan_interest)

**Pull request closed without merging**
