### PR TITLE
feat: run all recording files in directory with cli

### PR DESCRIPTION
**Pull request by puskuruk**
Implements #183 

- [X] Tests pass
- [X] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by OrKoN** [comment]
Hey, thanks for the PR. It looks like some tests are failing. Also I have been wondering if the shell filename expansion would work? Basically, the following already works in shells:

```
npx @puppeteer/replay replay*
Running replay.json...
Finished running replay.json
Running replay2.json...
Finished running replay2.json
```

**Comment by puskuruk** [comment]
Thank you for the feedback @OrKoN. I updated the PR and now all the tests pass. 💃 

Yes, shell filename expansion works. But when you want to run a folder with different files(like we have in [/test/resources](https://github.com/puppeteer/replay/tree/main/test/resources)) you should give the extension as well.
```bash
npx @puppeteer/replay replay*.json
```

With my pr it's easier. You just need to run the command below. It'll only run JSON files in the folder. 
```bash
npx @puppeteer/replay replay
```

If you think using shell filename expansion is a better approach, we should update the README. 🙏

**Comment by puskuruk** [comment]
Thank you for the feedback @OrKoN. I updated the PR and now all the tests pass. 💃 

Yes, shell filename expansion works. But when you want to run a folder with different files(like we have in [/test/resources](https://github.com/puppeteer/replay/tree/main/test/resources)) you should give the extension as well.
```bash
npx @puppeteer/replay replay/*.json
```

With my pr it's easier. You just need to run the command below. It'll only run JSON files in the folder. 
```bash
npx @puppeteer/replay replay
```

If you think using shell filename expansion is a better approach, we should update the README. 🙏

**Comment by puskuruk** [comment]
I saw the problem with Windows paths and I fixed it 🙏

**Comment by OrKoN** [comment]
Sounds good, could you please update the README with this? I think the code looks good.

**Comment by puskuruk** [comment]
Thank you @OrKoN !

I updated the README with this. You can check the last commit 🙏

**Review by OrKoN — APPROVED** [review]

**Comment by puskuruk** [comment]
There was a code style issue on README and I fixed it. Can you run GH actions again? @OrKoN

**Pull request merged**
