### PR TITLE
chore: fix eslint `no-unused-vars` error

### PR DESCRIPTION
**Pull request by puskuruk**
Fixes:

https://github.com/puppeteer/replay/blob/369c8238fb1294ab5758bf2945ac0c3c5d07cff5/test/cli.test.ts#L29-L34

- [X] Tests pass

Hi @ergunsh!

I solved the problem that you mentioned on your pr. Can you review it?

Reference: https://github.com/typescript-eslint/typescript-eslint/issues/2619#issuecomment-701901752

Have a nice day 🎉

### CODE REVIEW

**Review by ergunsh — APPROVED** [review]
LGTM, thank you :)

**Comment by puskuruk** [comment]
Thank you @ergunsh 🙏 

Workflows failed with the previous version and I pushed the branch again after updating `@typescript-eslint/no-unused-vars` from  `error` to `warn`.

**Comment by puskuruk** [comment]
Can we merge it? @jrandolf 🎉

**Comment by puskuruk** [comment]
Can you take a look at it again? @ergunsh 🙂

**Comment by puskuruk** [comment]
Thank you @jrandolf 🎉

**Comment by ergunsh** [comment]
Thanks for the fix! 🥳 

Though it seems to me that this is a rule that can be "error" indeed. Can we make it error and fix the issues in the meantime? :)

**Pull request merged**
